# Generated by Django 4.1.7 on 2023-03-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_cont', '0006_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
    ]
